[package]
name = "dioxus-bootstrap"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = {version = "0.5.6", features = ["web", "router"]}
wasm-bindgen = "0.2.92"
web-sys = {version = "0.3.69"}
serde_json = "1.0.116"
getrandom = { version = "0.2", features = ["js"] }
uuid = { version = "1.8.0", features = ["v4"] }
modx = "0.1.2"
dioxus-logger = { version = "0.5.1" }
tracing = "0.1.40"
log = "0.4.22"
once_cell = "1.19.0"
slab = "0.4.9"